name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: /Users/runner/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: /Users/runner/perl5
  PERL_MB_OPT: --install_base /Users/runner/perl5
  PERL_MM_OPT: INSTALL_BASE=/Users/runner/perl5
  PERL_CPANM_OPT: -M https://www.cpan.org

jobs:
  perl:

    runs-on: macOS-15-intel

    steps:
      - uses: actions/checkout@v4

      - name: Probe wd
        run: |
          pwd
          ls -l
          brew shellenv
          
      - name: Probe chip, homebrew etc
        run: |
          uname -m   
          echo $HOMEBREW_PREFIX
          ls /usr/lib/*.dylib
          

      - name: Install pkgconfig and fileicon
        run: |
          brew install pkgconfig
          brew install fileicon

      #  we use a shared alien for gdal and proj but this gets us the deps 
      #  otherwise we get issues with sqlite dylib clashes under homebrew
      #  no poppler due to https://github.com/osgeo/gdal/issues/13173 - handle as an arg when new Alien::gdal released
      - name: Install GDAL and its deps
        run: |
          brew install gdal boost
          # brew install curl expat zlib libxml2 libiconv
          # brew uninstall --ignore-dependencies poppler
        
        
      - name: Install Gtk etc
        run: brew install gdk-pixbuf pango gtk+3 glib gobject-introspection

      # - name: Gtk debug probes
      #   run: |
      #     find $HOMEBREW_PREFIX/lib -name libgtk-3.0.dylib
      #     ls $HOMEBREW_PREFIX/lib/girepository-1.0

      - name: Set up Perl
        run: |
          brew install perl
          curl https://cpanmin.us | perl - App::cpanminus -n
          # echo "##[add-path]/Users/runner/perl5/bin"
          echo "/Users/runner/perl5/bin" >> $GITHUB_PATH

      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          #  change the checksum so we refresh the cache
          echo 'intel with mostly shared Alien installs mk3' >> perlversion.txt
          ls -l perlversion.txt

      #- name: clear cache
      #  run: rm ~/perl5/${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Cache CPAN modules
        uses: actions/cache@v4
        if: "!cancelled()"
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install cpan deps 
        run: |
          #  ensure share install when needed
          eval "$(brew shellenv)"
          #cpanm Getopt::Long
          #cpanm App::PP::Autolink
          cpanm https://github.com/shawnlaffan/perl-pp-autolink.git@mac_intel_debug
          which pp_autolink.pl
          which -a pp
          #  no share install for Alien::MSYS
          cpanm --notest Alien::MSYS
          cpanm --notest Alien::libtiff  #  sys install for this one
          cpanm --notest Alien::patch
          # cpanm --notest Alien::sqlite
          ALIEN_INSTALL_TYPE=share cpanm --notest --installdeps Alien::gdal
          #  no poppler due to https://github.com/osgeo/gdal/issues/13173
          export ALIEN_GDAL_CONFIG_ARGS="-DGDAL_ENABLE_DRIVER_PDF:BOOL=OFF -DGDAL_USE_CURL=OFF"
          ALIEN_INSTALL_TYPE=share cpanm --notest -v Alien::gdal@1.43
          #ALIEN_INSTALL_TYPE=share cpanm --notest -v https://github.com/shawnlaffan/perl-alien-gdal.git
          #cpanm --notest Task::Biodiverse::NoGUI
          cpanm --notest ExtUtils::PkgConfig
          cpanm --notest ExtUtils::Depends
          cpanm --notest Glib::Object::Introspection
          cpanm --notest Gtk3
          cpanm --notest PAR::Packer
          cpanm --notest File::BaseDir
          cpanm --notest File::Find::Rule
          cpanm --notest Browser::Start
          cpanm --notest ExtUtils::Depends
          cpanm --notest HTTP::Tiny
          cpanm --notest IO::Socket::SSL
          cpanm --notest LWP::Simple
          cpanm --notest Geo::ShapeFile
          cpanm --notest autovivification
          otool -L `perl -MAlien::proj -E'print Alien::proj->dist_dir'`/lib/libproj.dylib
          otool -L `perl -MAlien::gdal -E'print Alien::gdal->dist_dir'`/lib/libgdal.dylib
          cpanm --installdeps --notest Geo::GDAL::FFI
          cpanm --reinstall --verbose Geo::GDAL::FFI || {
            echo "Geo::GDAL::FFI failed its tests" >&2
            cat $HOME/.cpanm/latest-build/build.log
            exit 0  #  don't cripple the caching by failing
          }
          
      - name: GDAL dylibs
        run: |
          which perl
          otool -L `perl -MAlien::gdal -E'print Alien::gdal->dist_dir'`/lib/libgdal.dylib
          

      - name: Clone biodiverse repo
        run: | 
          git clone --depth=1 https://github.com/shawnlaffan/biodiverse.git
          cd biodiverse
          cpanm --installdeps . || cat $HOME/.cpanm/latest-build/build.log
          prove t/00-load.t || true  #  allow caching even if we fail
          #prove -j4 -l t
          cd -
        
      - name: Upload cpanm dir
        if: success() || failure()
        uses: actions/upload-artifact@v4
        with:
          name: cpanm_dir
          path: ~/.cpanm
          
          
      - name: GDAL probe 1
        run: |
          perl etc/probe_gdal.pl
          pp_autolink -o probe_gdal etc/probe_gdal.pl
          ./probe_gdal || {
            echo "Binary failed to run!" >&2
            exit 0  #  don't cripple the caching by failing
          }


      #- name: Check Biodiverse can run, except that it hangs
      #  run: prove -l biodiverse/t
      
      - name: Resize dmg file
        run: |
          hdiutil resize -size 100MB ./images/Biodiverse.dmg
          df -h
      
      - name: Run mmb3.pl
        run: |
          eval "$(brew shellenv)"
          export PATH=/Users/runner/perl5/bin:$PATH
          which -a pp
          echo $SHELL
          perl bin/mmb3.pl -v -s biodiverse/bin/BiodiverseGUI.pl
        
      - name: Find dmg file
        run: |
          export DMG_FILE_NAME=`find ./builds -name Biodiverse-*.dmg -print`
          echo ${DMG_FILE_NAME}
          
        
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: dmg-file
          #path: ${DMG_FILE_NAME}
          path: ./builds/Biodiverse-*.dmg

      - name: Uninstall brew deps
        run: |
          brew uninstall --ignore-dependencies gdk-pixbuf gtk+3 gdal proj


      - name: Try to run the packed archive
        run: |
          BDV_PP_BUILDING=1 BD_NO_GUI_DEV_WARN=1 ./builds/Biodiverse.app/Contents/MacOS/BiodiverseGUI || {
            echo "Binary failed to run!" >&2
            exit 0  #  don't cripple the caching by failing
          }
          
          
      - name: GDAL probe 2
        run: |
          ./probe_gdal || {
            echo "Binary failed to run!" >&2
            exit 0  #  don't cripple the caching by failing
          }

      - name: Upload gdal probe
        uses: actions/upload-artifact@v4
        with:
          name: gdal_probe
          path: ./probe_gdal