name: macos

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

env:
  PERL5LIB: /Users/runner/perl5/lib/perl5
  PERL_LOCAL_LIB_ROOT: /Users/runner/perl5
  PERL_MB_OPT: --install_base /Users/runner/perl5
  PERL_MM_OPT: INSTALL_BASE=/Users/runner/perl5
  PERL_CPANM_OPT: -M https://www.cpan.org

jobs:
  perl:

    runs-on: macOS-15-intel

    steps:
      - uses: actions/checkout@v4

      - name: Probe wd
        run: |
          pwd
          ls -l
          brew shellenv
          
      - name: Probe chip and homebrew
        run: |
          uname -m   
          echo $HOMEBREW_PREFIX
          

      - name: Install pkgconfig and fileicon
        run: |
          brew install pkgconfig
          brew install fileicon

      #  we use a shared alien for gdal and proj but this gets us the deps 
      #  otherwise we get issues with sqlite dylib clashes under homebrew
      #  We need boost or the build fails
      - name: Install GDAL and its deps
        run: brew install gdal boost
        
        
      - name: Install Gtk etc
        run: brew install gdk-pixbuf pango gtk+3 glib gobject-introspection

      # - name: Gtk debug probes
      #   run: |
      #     find $HOMEBREW_PREFIX/lib -name libgtk-3.0.dylib
      #     ls $HOMEBREW_PREFIX/lib/girepository-1.0

      - name: Set up Perl
        run: |
          brew install perl
          curl https://cpanmin.us | perl - App::cpanminus -n
          # echo "##[add-path]/Users/runner/perl5/bin"
          echo "/Users/runner/perl5/bin" >> $GITHUB_PATH

      - name: perl -V
        run: perl -V

      - name: Prepare for cache
        run: |
          perl -V > perlversion.txt
          #  change the checksum so we refresh the cache
          echo 'intel with mostly shared Alien installs' >> perlversion.txt
          ls -l perlversion.txt

      #- name: clear cache
      #  run: rm ~/perl5/${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Cache CPAN modules
        uses: actions/cache@v4
        if: "!cancelled()"
        with:
          path: ~/perl5
          key: ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ hashFiles('perlversion.txt') }}

      - name: Install cpan deps 
        run: |
          #cpanm Getopt::Long
          #cpanm App::PP::Autolink
          cpanm https://github.com/shawnlaffan/perl-pp-autolink.git@mac_intel_debug
          which pp_autolink.pl
          which -a pp
          #  no share install for Alien::MSYS
          cpanm --notest Alien::MSYS
          cpanm --notest Alien::libtiff  #  sys install for this one
          #  ensure share install for gdal et al
          echo HHH
          echo $HOMEBREW_PREFIX
          export HOMEBREW_PREFIX=`brew --prefix`
          echo $HOMEBREW_PREFIX
          echo HHH
          cpanm --notest Alien::patch
          ALIEN_INSTALL_TYPE=share cpanm --notest --installdeps Alien::gdal
          #ALIEN_INSTALL_TYPE=share cpanm --notest -v Alien::gdal
          ALIEN_INSTALL_TYPE=share cpanm --notest -v https://github.com/shawnlaffan/perl-alien-gdal.git
          #cpanm --notest Task::Biodiverse::NoGUI
          cpanm --notest ExtUtils::PkgConfig
          cpanm --notest ExtUtils::Depends
          cpanm --notest Glib::Object::Introspection
          cpanm --notest Gtk3
          cpanm --notest PAR::Packer
          cpanm --notest File::BaseDir
          cpanm --notest File::Find::Rule
          cpanm --notest Browser::Start
          cpanm --notest ExtUtils::Depends
          cpanm --notest HTTP::Tiny
          cpanm --notest IO::Socket::SSL
          cpanm --notest LWP::Simple
          cpanm --notest Geo::ShapeFile
          cpanm --notest autovivification
          
      - name: GDAL dylibs
        run: |
          which perl
          otool -L `perl -MAlien::GDAL -E'print Alien::gdal->dist_dir'`/lib/libgdal.dylib
          
      # - name: GDAL probe
        # run: |
          # perl etc/probe_gdal.pl
          # pp_autolink -o probe_gdal etc/probe_gdal
          # ./probe_gdal || {
            # echo "Binary failed to run!" >&2
            # exit 0  #  don't cripple the caching by failing
          # }

      - name: Clone biodiverse repo
        run: | 
          git clone --depth=1 https://github.com/shawnlaffan/biodiverse.git
          cd biodiverse
          cpanm --installdeps .
          prove t/00-load.t
          #prove -j4 -l t
          cd -
        
      #- name: Check Biodiverse can run, except that it hangs
      #  run: prove -l biodiverse/t
      
      - name: Resize dmg file
        run: |
          hdiutil resize -size 100MB ./images/Biodiverse.dmg
          df -h
      
      - name: Run mmb3.pl
        run: |
          eval "$(brew shellenv)"
          export PATH=/Users/runner/perl5/bin:$PATH
          which -a pp
          echo $SHELL
          perl bin/mmb3.pl -v -s biodiverse/bin/BiodiverseGUI.pl
        
      - name: Find dmg file
        run: |
          export DMG_FILE_NAME=`find ./builds -name Biodiverse-*.dmg -print`
          echo ${DMG_FILE_NAME}
          
        
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: dmg-file
          #path: ${DMG_FILE_NAME}
          path: ./builds/Biodiverse-*.dmg

      - name: Uninstall brew deps
        run: |
          brew uninstall gdk-pixbuf gtk+3

#  Re-enable for debugging as it does not exit immediately      
#      - name: Try to run the packed archive
#        run: |
#          BDV_PP_BUILDING=1 ./builds/Biodiverse.app/Contents/MacOS/BiodiverseGUI || {
#            echo "Binary failed to run!" >&2
#            exit 0  #  don't cripple the caching by failing
#          }
          